/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomiciliosRouteImport } from './routes/domicilios'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as PerfilPopulacaoRouteImport } from './routes/perfil-populacao'
import { Route as PessoasComDeficienciaRouteImport } from './routes/pessoas-com-deficiencia'
import { Route as RendaVulnerabilidadeRouteImport } from './routes/renda-vulnerabilidade'
import { Route as TrabalhoRendaRouteImport } from './routes/trabalho-renda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomiciliosRoute = DomiciliosRouteImport.update({
  id: '/domicilios',
  path: '/domicilios',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilPopulacaoRoute = PerfilPopulacaoRouteImport.update({
  id: '/perfil-populacao',
  path: '/perfil-populacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasComDeficienciaRoute = PessoasComDeficienciaRouteImport.update({
  id: '/pessoas-com-deficiencia',
  path: '/pessoas-com-deficiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RendaVulnerabilidadeRoute = RendaVulnerabilidadeRouteImport.update({
  id: '/renda-vulnerabilidade',
  path: '/renda-vulnerabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhoRendaRoute = TrabalhoRendaRouteImport.update({
  id: '/trabalho-renda',
  path: '/trabalho-renda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domicilios': typeof DomiciliosRoute
  '/educacao': typeof EducacaoRoute
  '/familias': typeof FamiliasRoute
  '/perfil-populacao': typeof PerfilPopulacaoRoute
  '/pessoas-com-deficiencia': typeof PessoasComDeficienciaRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
  '/trabalho-renda': typeof TrabalhoRendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domicilios': typeof DomiciliosRoute
  '/educacao': typeof EducacaoRoute
  '/familias': typeof FamiliasRoute
  '/perfil-populacao': typeof PerfilPopulacaoRoute
  '/pessoas-com-deficiencia': typeof PessoasComDeficienciaRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
  '/trabalho-renda': typeof TrabalhoRendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domicilios': typeof DomiciliosRoute
  '/educacao': typeof EducacaoRoute
  '/familias': typeof FamiliasRoute
  '/perfil-populacao': typeof PerfilPopulacaoRoute
  '/pessoas-com-deficiencia': typeof PessoasComDeficienciaRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
  '/trabalho-renda': typeof TrabalhoRendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domicilios'
    | '/educacao'
    | '/familias'
    | '/perfil-populacao'
    | '/pessoas-com-deficiencia'
    | '/renda-vulnerabilidade'
    | '/trabalho-renda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domicilios'
    | '/educacao'
    | '/familias'
    | '/perfil-populacao'
    | '/pessoas-com-deficiencia'
    | '/renda-vulnerabilidade'
    | '/trabalho-renda'
  id:
    | '__root__'
    | '/'
    | '/domicilios'
    | '/educacao'
    | '/familias'
    | '/perfil-populacao'
    | '/pessoas-com-deficiencia'
    | '/renda-vulnerabilidade'
    | '/trabalho-renda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomiciliosRoute: typeof DomiciliosRoute
  EducacaoRoute: typeof EducacaoRoute
  FamiliasRoute: typeof FamiliasRoute
  PerfilPopulacaoRoute: typeof PerfilPopulacaoRoute
  PessoasComDeficienciaRoute: typeof PessoasComDeficienciaRoute
  RendaVulnerabilidadeRoute: typeof RendaVulnerabilidadeRoute
  TrabalhoRendaRoute: typeof TrabalhoRendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domicilios': {
      id: '/domicilios'
      path: '/domicilios'
      fullPath: '/domicilios'
      preLoaderRoute: typeof DomiciliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-populacao': {
      id: '/perfil-populacao'
      path: '/perfil-populacao'
      fullPath: '/perfil-populacao'
      preLoaderRoute: typeof PerfilPopulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas-com-deficiencia': {
      id: '/pessoas-com-deficiencia'
      path: '/pessoas-com-deficiencia'
      fullPath: '/pessoas-com-deficiencia'
      preLoaderRoute: typeof PessoasComDeficienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renda-vulnerabilidade': {
      id: '/renda-vulnerabilidade'
      path: '/renda-vulnerabilidade'
      fullPath: '/renda-vulnerabilidade'
      preLoaderRoute: typeof RendaVulnerabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalho-renda': {
      id: '/trabalho-renda'
      path: '/trabalho-renda'
      fullPath: '/trabalho-renda'
      preLoaderRoute: typeof TrabalhoRendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomiciliosRoute: DomiciliosRoute,
  EducacaoRoute: EducacaoRoute,
  FamiliasRoute: FamiliasRoute,
  PerfilPopulacaoRoute: PerfilPopulacaoRoute,
  PessoasComDeficienciaRoute: PessoasComDeficienciaRoute,
  RendaVulnerabilidadeRoute: RendaVulnerabilidadeRoute,
  TrabalhoRendaRoute: TrabalhoRendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
