/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as RendaVulnerabilidadeRouteImport } from './routes/renda-vulnerabilidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const RendaVulnerabilidadeRoute = RendaVulnerabilidadeRouteImport.update({
  id: '/renda-vulnerabilidade',
  path: '/renda-vulnerabilidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/familias': typeof FamiliasRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/familias': typeof FamiliasRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/familias': typeof FamiliasRoute
  '/renda-vulnerabilidade': typeof RendaVulnerabilidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/familias' | '/renda-vulnerabilidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/familias' | '/renda-vulnerabilidade'
  id: '__root__' | '/' | '/familias' | '/renda-vulnerabilidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliasRoute: typeof FamiliasRoute
  RendaVulnerabilidadeRoute: typeof RendaVulnerabilidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renda-vulnerabilidade': {
      id: '/renda-vulnerabilidade'
      path: '/renda-vulnerabilidade'
      fullPath: '/renda-vulnerabilidade'
      preLoaderRoute: typeof RendaVulnerabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliasRoute: FamiliasRoute,
  RendaVulnerabilidadeRoute: RendaVulnerabilidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
